spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${admin.db.username}
    password: ${admin.db.password}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: ${admin.h2.enabled}
      path: /h2-console/
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
security:
  apiKey: ${admin.security.apiKey}
  allowedOrigins:
    - ${admin.security.allowedOrigin1}